### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by limzx0307** [limzx0307/tictactoegame.github.io#1]
Add new feature

## TODO

- [ ] Add more style
- [ ] Add sound effect for winning
- [ ] Add a pop up screen for winning
- [ ] Add a scoreboard for game history
